// ═══════════════════════════════════════════════════════════════
// REMOTION COMPOSITION SCAFFOLD
// Digital Alchemy Studio — Video Rendering Pipeline
// ═══════════════════════════════════════════════════════════════
//
// This file is the starting point for the Remotion video pipeline.
// It mirrors the interactive React component but uses Remotion's
// frame-based timing for precise subliminal placement and
// entrainment synchronization.
//
// Setup:
//   npx create-video@latest digital-alchemy-video
//   cd digital-alchemy-video
//   npm install
//   Copy this file to src/compositions/AlchemyComposition.tsx
//
// Usage:
//   npx remotion render AlchemyComposition out/meditation.mp4
//
// ═══════════════════════════════════════════════════════════════

import React from 'react';
// import { AbsoluteFill, useCurrentFrame, useVideoConfig, Sequence, interpolate } from 'remotion';

// ── Type definitions for Composition Recipes ──────────────────

interface TemporalPhase {
  start: number;  // 0-1 normalized
  end: number;
  state: string;
}

interface LayerConfig {
  type: 'background_field' | 'sacred_geometry' | 'particle_system' | 
        'subliminal_text' | 'subliminal_symbols' | 'entrainment' | 'vignette';
  // Each type has its own params
  [key: string]: any;
}

interface CompositionRecipe {
  intention: string;
  title: string;
  duration_seconds: number;
  resolution: { width: number; height: number };
  fps: number;
  
  temporal_arc: {
    opening: TemporalPhase;
    descent: TemporalPhase;
    core: TemporalPhase;
    integration: TemporalPhase;
    closing: TemporalPhase;
  };
  
  layers: LayerConfig[];
  
  subliminals: {
    messages: string[];
    opacity_range: [number, number];
    schedule: 'low_density' | 'medium_density' | 'high_density' | 'peak_density';
  };
  
  entrainment: {
    start_hz: number;
    end_hz: number;
    curve: 'linear' | 'exponential' | 'stepped';
    depth: number;
  };
  
  color_palette: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
  };
  
  geometry: {
    form: string;
    params: Record<string, any>;
  };
  
  symbols: string[];
  breath_cycle_seconds: number;
}

// ── Example Recipe (generated by LLM agent) ───────────────────

const EXAMPLE_RECIPE: CompositionRecipe = {
  intention: "healing",
  title: "Cellular Renewal Field",
  duration_seconds: 600,  // 10 minutes
  resolution: { width: 1920, height: 1080 },
  fps: 60,
  
  temporal_arc: {
    opening:     { start: 0,    end: 0.12, state: "grounding" },
    descent:     { start: 0.12, end: 0.30, state: "deepening" },
    core:        { start: 0.30, end: 0.75, state: "peak_healing" },
    integration: { start: 0.75, end: 0.90, state: "integration" },
    closing:     { start: 0.90, end: 1.0,  state: "return" }
  },
  
  layers: [
    { type: "background_field", style: "nebula_gradient", colors: ["#020d1a", "#071e2c", "#0a2d3a"] },
    { type: "sacred_geometry", form: "flower_of_life", rings: 3, color: "#00ff88" },
    { type: "particle_system", count: 200, behavior: "orbital" },
    { type: "subliminal_text" },
    { type: "subliminal_symbols" },
    { type: "entrainment" },
    { type: "vignette" }
  ],
  
  subliminals: {
    messages: [
      "Every cell renews with light",
      "Healing flows through me now",
      "I am whole and complete",
      "My body is a temple of vitality",
      "Life force surges within me",
      "I radiate perfect health",
      "Restoration is my nature",
      "Wellness is my birthright",
      "I release what no longer serves me",
      "Divine healing fills every fiber",
      "I am grateful for my body's wisdom",
      "Health and harmony are mine",
      "I trust my body's ability to heal",
      "Every breath brings renewal",
      "I am aligned with perfect health"
    ],
    opacity_range: [0.02, 0.05],
    schedule: "medium_density"
  },
  
  entrainment: {
    start_hz: 12,    // Start in alpha
    end_hz: 6,       // Descend to theta
    curve: "exponential",
    depth: 0.12
  },
  
  color_palette: {
    primary: "#00ff88",
    secondary: "#4169E1",
    accent: "#FFD700",
    background: "#020d1a"
  },
  
  geometry: {
    form: "flower_of_life",
    params: { rings: 3, rotation_speed: 0.1 }
  },
  
  symbols: ["✦", "❋", "◉", "⊕", "☽", "☀"],
  breath_cycle_seconds: 11
};

// ── Remotion Composition (uncomment when in Remotion project) ──

/*
export const AlchemyComposition: React.FC<{ recipe: CompositionRecipe }> = ({ recipe }) => {
  const frame = useCurrentFrame();
  const { fps, width, height, durationInFrames } = useVideoConfig();
  
  const progress = frame / durationInFrames;  // 0-1
  const time = frame / fps;                   // seconds
  
  // Determine current phase
  const getCurrentPhase = () => {
    const arc = recipe.temporal_arc;
    if (progress < arc.opening.end) return 'opening';
    if (progress < arc.descent.end) return 'descent';
    if (progress < arc.core.end) return 'core';
    if (progress < arc.integration.end) return 'integration';
    return 'closing';
  };
  
  const phase = getCurrentPhase();
  
  // Entrainment frequency at current time
  const getFrequency = () => {
    const { start_hz, end_hz, curve } = recipe.entrainment;
    if (curve === 'linear') return start_hz + (end_hz - start_hz) * progress;
    if (curve === 'exponential') return start_hz * Math.pow(end_hz / start_hz, progress);
    return start_hz; // stepped handled separately
  };
  
  const currentHz = getFrequency();
  const entrainmentMod = 1 + Math.sin(2 * Math.PI * currentHz * time) * recipe.entrainment.depth;
  
  // Subliminal scheduling - determines which frames show subliminal text
  const subliminalDensity = {
    low_density: 0.2,
    medium_density: 0.5,
    high_density: 2.0,
    peak_density: 3.0
  }[recipe.subliminals.schedule];
  
  // Deterministic subliminal placement (seeded by frame number)
  const showSubliminal = (frame % Math.floor(fps / subliminalDensity)) === 0;
  const subliminalIndex = frame % recipe.subliminals.messages.length;
  
  return (
    <AbsoluteFill style={{ backgroundColor: recipe.color_palette.background }}>
      
      {/* Layer 0: Background */}
      {/* <BackgroundField colors={recipe.layers[0].colors} time={time} /> */}
      
      {/* Layer 1: Sacred Geometry */}
      {/* <SacredGeometry 
        form={recipe.geometry.form}
        params={recipe.geometry.params}
        color={recipe.color_palette.primary}
        time={time}
        entrainment={entrainmentMod}
      /> */}
      
      {/* Layer 2: Particles */}
      {/* <ParticleSystem
        count={200}
        behavior={recipe.layers[2].behavior}
        color={recipe.color_palette.primary}
        time={time}
      /> */}
      
      {/* Layer 3: Subliminal Text */}
      {showSubliminal && (
        <AbsoluteFill>
          <div style={{
            position: 'absolute',
            left: `${(frame * 7919) % 80 + 5}%`,
            top: `${(frame * 6271) % 80 + 5}%`,
            color: recipe.color_palette.secondary,
            opacity: recipe.subliminals.opacity_range[0] + 
              Math.random() * (recipe.subliminals.opacity_range[1] - recipe.subliminals.opacity_range[0]),
            fontSize: 14,
            fontFamily: 'Georgia, serif',
            pointerEvents: 'none'
          }}>
            {recipe.subliminals.messages[subliminalIndex]}
          </div>
        </AbsoluteFill>
      )}
      
      {/* Layer 4: Entrainment Overlay */}
      <AbsoluteFill style={{
        backgroundColor: `rgba(255,255,255,${(entrainmentMod - 1 + recipe.entrainment.depth) * 0.25})`,
        mixBlendMode: 'overlay'
      }} />
      
      {/* Layer 5: Vignette */}
      <AbsoluteFill style={{
        background: 'radial-gradient(circle, transparent 30%, rgba(0,0,0,0.7) 100%)',
        pointerEvents: 'none'
      }} />
      
      {/* Phase-based transitions */}
      {phase === 'opening' && (
        <AbsoluteFill style={{
          backgroundColor: 'black',
          opacity: interpolate(
            progress,
            [0, recipe.temporal_arc.opening.end],
            [1, 0]
          )
        }} />
      )}
      
      {phase === 'closing' && (
        <AbsoluteFill style={{
          backgroundColor: 'black',
          opacity: interpolate(
            progress,
            [recipe.temporal_arc.closing.start, 1],
            [0, 1]
          )
        }} />
      )}
      
    </AbsoluteFill>
  );
};
*/

// ── Remotion Registration (uncomment in Root.tsx) ──

/*
import { Composition } from 'remotion';
import { AlchemyComposition } from './compositions/AlchemyComposition';

export const RemotionRoot: React.FC = () => {
  const recipe = EXAMPLE_RECIPE;
  return (
    <Composition
      id="AlchemyComposition"
      component={AlchemyComposition}
      durationInFrames={recipe.duration_seconds * recipe.fps}
      fps={recipe.fps}
      width={recipe.resolution.width}
      height={recipe.resolution.height}
      defaultProps={{ recipe }}
    />
  );
};
*/

// ── Export for reference ──
export { EXAMPLE_RECIPE };
export type { CompositionRecipe, TemporalPhase, LayerConfig };
